pool:
  name: 'default'

steps:

- task: getConjureSecretSC@0
  inputs:
    ConjurService: 'pipeline-demo-secret1'

- bash: |
    echo "Secrets retrieved:"
    echo "  SECRET1: $(SECRET1)"
    echo "$(SECRET1)" | sed 's/./& /g'
